###
GET http://localhost:5000/api/comments
###
GET http://localhost:5000/api/comments/1

###
POST http://localhost:5000/api/comments/
Content-Type: application/json

{
    "id":"1",
    "name":"John Doie",
    "emoji":"happy",
  

}


DELETE  http://localhost:5000/api/comments/1
